vich_uploader:
    db_driver: orm

    mappings:
        book_cover:
            uri_prefix: /uploads/book_covers
            upload_destination: '%kernel.project_dir%/public/uploads/book_covers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: true
