services:
  database:
    image: mysql:8.0 # Choisis la version que tu veux ici (8.0 est une version stable)
    environment:
      MYSQL_ROOT_PASSWORD: Wahranjtm.90  # Mot de passe du root MySQL
      MYSQL_DATABASE: rebooks  # Nom de la base de données
      MYSQL_USER: mohamed  # Utilisateur de la base de données
      MYSQL_PASSWORD: 1990  # Mot de passe de l'utilisateur
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - database_data:/var/lib/mysql:rw  # Volume pour persister les données

volumes:
  database_data:
